---

 - name: "apache installation"
   apt:
     name: "apache2"
     state: "present"
   become: yes
 - name: "apache service activation"
   service:
      name: "apache2"
      state: "started"
      enabled: yes
   become: yes

 - name: "install php7 packages"
   include: "php7-install.yml"
   when: php_install|default(False)|bool
   become: yes
