---
# tasks file for mariadb


# Installation des paquets mariadb serveur et son extension Python
 - name: "mariadb-server installation"
   apt:
     name:  "mariadb-server"
     state: "installed"
   become: yes
 - name: "python-mysqldb"
   apt:
     name:  "python-mysqldb"
     state: "installed"
   become: yes

#   # Active le service MariaDB 
 - name: "start mariadb service"
   service:
       name:  "mariadb"
       state: "started"
       enabled: yes
   become: yes
