---
# tasks file for confdb


#1. Installation de la base de donnée Mediawiki
- name: "mediawiki database"
  mysql_db:
    name: "{{mediawiki_db_name}}"
    state: present
    become: yes
#  #2. Création d’un accès utilisateur et attribution des privilèges sur la base Mediawiki
- name: "mediawiki user+privileges"
  mysql_user:
      name: "{{mediawiki_db_user}}"
      password: "{{mediawiki_db_password}}"
      priv: "{{mediawiki_db_name}}.*:ALL"
      host: "{{item}}"
      state: present
  with_items: "{{groups.apache}}"
  become: yes
